#if !canImport(ObjectiveC)
import XCTest

extension InlinableTestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InlinableTestTests = [
        ("testInlined", testInlined),
        ("testInlined2", testInlined2),
        ("testNotInlined", testNotInlined),
        ("testNotInlined2", testNotInlined2),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(InlinableTestTests.__allTests__InlinableTestTests),
    ]
}
#endif
